# Generated by Django 2.1.7 on 2019-04-09 00:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAluno', models.CharField(max_length=255)),
                ('cursoAluno', models.CharField(max_length=50)),
                ('salaAluno', models.CharField(max_length=1)),
                ('cpfAluno', models.CharField(max_length=14)),
                ('serieAluno', models.IntegerField()),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
