# Generated by Django 2.1.7 on 2019-04-27 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
