# Generated by Django 2.1.7 on 2019-04-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='imagemAluno',
            field=models.ImageField(default=1, upload_to='images/alunos'),
            preserve_default=False,
        ),
    ]
