# Generated by Django 2.1.7 on 2019-04-23 00:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('votacoes', '0002_aluno_imagemaluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('votosP', models.IntegerField(default=0)),
                ('votosN', models.IntegerField(default=0)),
                ('concluida', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelManagers(
            name='aluno',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='salaAluno',
            new_name='turmaAluno',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='serieAluno',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AddField(
            model_name='votacao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.Aluno'),
        ),
    ]
